prog:scrolling.o input.o collision.o vie.o perso.o map.o ennemi.o main.o 
	gcc scrolling.o input.o collision.o vie.o perso.o map.o ennemi.o main.o   -lSDL -lSDL_image  -o prog

main.o:main.c
	gcc -c main.c

ennemi.o:ennemi.c
	gcc -c ennemi.c

map.o:map.c
	gcc -c map.c

perso.o:perso.c
	gcc -c perso.c

vie.o:vie.c
	gcc -c vie.c

collision.o:collision.c
	gcc -c collision.c

scrolling.o:scrolling.c
	gcc -c scrolling.c

input.o:input.c
	gcc -c input.c


