prog:scrolling.o input.o perso.o map.o main.o 
	gcc scrolling.o input.o perso.o map.o main.o -lSDL -lSDL_image -lSDL_mixer -o prog

main.o:main.c
	gcc -c main.c

map.o:map.c
	gcc -c map.c

perso.o:perso.c
	gcc -c perso.c

scrolling.o:scrolling.c
	gcc -c scrolling.c

input.o:input.c
	gcc -c input.c
